# Generated by Django 3.0.5 on 2022-05-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_img_url',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
