# Generated by Django 3.0.5 on 2022-05-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_pizza_pizza_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='commentor_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
